version: '3'

services:

  rc_db:
    image: postgres:13
    environment:
      POSTGRES_USER: racoondb
      POSTGRES_PASSWORD: racoondb
      POSTGRES_DB: racoondb
    ports:
      - "5432:5432"

  rc_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    depends_on:
      - rc_db